# RTL and Testbench File List
# Generated by 'make update_list'
# Date: Sun May 31 14:57:53 EEST 2026
# Project: clk_lib

# RTL Source Files
sources/rtl/STD_MODULES.v
sources/rtl/clk_div2.sv
sources/rtl/clk_div_even.sv
sources/rtl/clk_div_prog.sv

# Testbench Files
sources/tb/clk_div2_tb.sv
sources/tb/clk_div_even_tb.sv
sources/tb/clk_div_prog_tb.sv
